### ISSUE TITLE
Installing multiple packages via Intune does not seem to work

### ISSUE THREAD

**Issue by hennibadger16** [Romanitho/Winget-Install#1]
Great tool! Thanks a lot for your effort.

Unfortunately the installation of multiple packages in one via Intune does not seem to work. As I understand it, I would have to use
"powershell.exe -ExecutionPolicy bypass -File winget-install.ps1 -AppIDs 7zip.7zip,notepad++.notepad++" as a install command?!

For the sake of testing I just detected the presence of one package. Both apps are not installed. Intune says the detection rule could not be satisfied. I guess it has something to do with the handling of multiple apps via "-AppIDs x,y"?

Edit:
Yeah - it seems it got problems parsing multiple AppIDs:
>> 14:09:06 - 7zip.7zip,notepad++.notepad++ does not exist on Winget Repository! Check spelling.

Any way around it? 

Thank you very much :)

**Comment by Frxhb** [comment]
I have a similar problem, when I try to install more than one app, have a look:

`C:\ProgramData>powershell.exe -NoProfile -ExecutionPolicy Bypass -File %ProgramData%\winget-install.ps1 -AppIDs "7zip.7zip, Adobe.Acrobat.Reader.64-bit, Git.Git, Google.Chrome, PDFsam.PDFsam, DominikReichl.KeePass, Mozilla.Firefox.ESR, Greenshot.Greenshot, IrfanSkiljan.Irfanview"`



```
08:12:18 - ###   09.02.2024 - NEW INSTALL REQUEST   ###

08:12:18 - Running with admin rights.

08:12:18 - Checking prerequisites...
08:12:19 - Installed Winget version: v1.6.3482
08:12:19 - Checking prerequisites ended.

08:12:20 - Start 7zip.7zip, processing...
08:12:20 - -> 7zip.7zip, does not exist on Winget Repository! Check spelling.
08:12:20 - 7zip.7zip, processing finished!

08:12:21 - ###   END REQUEST   ###
```

`C:\ProgramData>winget search 7zip`

```
Name              ID                     Version            Übereinstimmung Quelle
----------------------------------------------------------------------------------
7-Zip             7zip.7zip              23.01              Moniker: 7zip   winget
7-Zip ZS          mcmilk.7zip-zstd       22.01 ZS v1.5.5 R2 Tag: 7zip       winget
NanaZip Preview   M2Team.NanaZip.Preview 3.0.756.0          Tag: 7zip       winget
NanaZip           M2Team.NanaZip         2.0.450.0          Tag: 7zip       winget
7-Zip Alpha (msi) 7zip.7zip.Alpha.msi    21.03.00.0                         winget
7-Zip Alpha (exe) 7zip.7zip.Alpha.exe    23.00                              winget
```

`C:\ProgramData>powershell.exe -NoProfile -ExecutionPolicy Bypass -File %ProgramData%\winget-install.ps1 -AppIDs 7zip.7zip,Adobe.Acrobat.Reader.64-bit,Git.Git,Google.Chrome,PDFsam.PDFsam,DominikReichl.KeePass,Mozilla.Firefox.ESR,Greenshot.Greenshot,IrfanSkiljan.Irfanview
`

```
08:12:46 - ###   09.02.2024 - NEW INSTALL REQUEST   ###

08:12:46 - Running with admin rights.

08:12:46 - Checking prerequisites...
08:12:47 - Installed Winget version: v1.6.3482
08:12:47 - Checking prerequisites ended.

08:12:47 - Start 7zip.7zip,Adobe.Acrobat.Reader.64-bit,Git.Git,Google.Chrome,PDFsam.PDFsam,DominikReichl.KeePass,Mozilla.Firefox.ESR,Greenshot.Greenshot,IrfanSkiljan.Irfanview processing...
08:12:48 - -> 7zip.7zip,Adobe.Acrobat.Reader.64-bit,Git.Git,Google.Chrome,PDFsam.PDFsam,DominikReichl.KeePass,Mozilla.Firefox.ESR,Greenshot.Greenshot,IrfanSkiljan.Irfanview does not exist on Winget Repository! Check spelling.
08:12:48 - 7zip.7zip,Adobe.Acrobat.Reader.64-bit,Git.Git,Google.Chrome,PDFsam.PDFsam,DominikReichl.KeePass,Mozilla.Firefox.ESR,Greenshot.Greenshot,IrfanSkiljan.Irfanview processing finished!

08:12:49 - ###   END REQUEST   ###
```

**Comment by Frxhb** [comment]
This is working:
