### ISSUE TITLE
Apps not installing in true system context

### ISSUE THREAD

**Issue by durrante** [Romanitho/Winget-Install#100]
Hi there,

Just to let you know that when installing applications, they do not appear to be installing in true system context, for example, take the Azure Data Studio application, when installed via Intune, it installs into the System profile, rather than being specified to install for all users, so the installation is placed with the system profile at this location: 

![image](https://github.com/Romanitho/Winget-Install/assets/64601521/87a74558-f328-4503-a5d9-b91354369eea)

However, the application is not available to any users:

![image](https://github.com/Romanitho/Winget-Install/assets/64601521/c4023161-a630-44cb-994f-20a3ed3282df)

Logs: 
![image](https://github.com/Romanitho/Winget-Install/assets/64601521/2d6e115b-7e98-4913-8d1d-97eb7357e957)

I think what is missing is the --scope machine parameter on the installation commands. 

Here's the intune app, it's specified as system:

![image](https://github.com/Romanitho/Winget-Install/assets/64601521/171f63b9-cc44-4601-9768-b3c01b9fec4f)

**Comment by Romanitho** [comment]
you can add the scope in your install command.

**Comment by durrante** [comment]
Hi there, 

I thought it did this automatically? I can see a function for machine scope? I'm using your intuneGUI, is it a simple case of adding an additional parameter of '--scope machine'

**Comment by durrante** [comment]
Hi there, 

Was wondering if you saw my previous comment? :)

**Comment by Romanitho** [comment]
it sometimes depend on the apps themselves.

**Comment by durrante** [comment]
> it sometimes depend on the apps themselves.

Thanks :), so in your tool, do I specify '--scope machine' in the command line parameters?

**Comment by Romanitho** [comment]
you can. normally it is designed to put it in the Winget Config.
