### ISSUE TITLE
Intune system install - not installing with scope machine

### ISSUE THREAD

**Issue by Matteo961** [Romanitho/Winget-Install#107]
Hi,

If I understand correctly. The script identifies the script execution context and if that is system, it should add the '--scope machine' flag.
When I check the logs with apps I have defined in Intune to run as system, I don't see it added.

Example:

-> Running: "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.22.10582.0_x64__8wekyb3d8bbwe\winget.exe" install --id 7zip.7zip -e --accept-package-agreements --accept-source-agreements -s winget -h 

Am I missing something here or is this a issue ?
I am not specifying anything special in the install command just the AppId's.

Thanks !

**Comment by Romanitho** [comment]
Hi,
If the script runs in system context, it specifies the preferred scope to "machine". then it depends on the app itself. it never forces the '--scope machine'.
In your example, if you run the script with admin rights, it should specify "machine" in the settings as preferred method.

**Comment by Matteo961** [comment]
Hi, thanks for the feedback.
So you mean adding "-machine" after the appid ?

**Comment by Romanitho** [comment]
not sure to understand.
You don't have anything to add. it should by default run for the machine
