### ISSUE TITLE
--id parameter could probably be removed

### ISSUE THREAD

**Issue by ThomasHoins** [Romanitho/Winget-Install#109]
Unfortunately you used the --id parameter to find or install via winget, that makes it impossible to use the moniker or the ID. 
You could probably just leave the parameter away. I tested it in my project where that worked fine. I'm not sure if that would work with the extra plugins or your UI.

**Comment by Romanitho** [comment]
it is historical. It used to have a buggy version of Winget that was causing issues if a source was not explicitly specified.
Today it could probably be removed...

**Comment by Romanitho** [comment]
Just noticed that I replied to your #108 other post here 😅
