### ISSUE TITLE
Install in user context

### ISSUE THREAD

**Issue by arafelp** [Romanitho/Winget-Install#115]
Sorry, but is there a similar way to install as a user (not admin) with a previous update\install of winget?

**Comment by FaserF** [comment]
Winget-install has moved: https://github.com/Romanitho/Winget-AutoUpdate/blob/main/Sources/Winget-AutoUpdate/Winget-Install.ps1

But yes, for me this repo here worked always great without issues for user installations (if the winget app supports it).
With the new winget-install for me currently there is an issue: https://github.com/Romanitho/Winget-AutoUpdate/issues/752
