### ISSUE TITLE
AppInstallerCLI.exe renamed in winget v1.2

### ISSUE THREAD

**Issue by o-l-a-v** [Romanitho/Winget-Install#2]
Just a headsup that AppInstallerCLI.exe was renamed to winget.exe in winget v1.2. :) Which breaks system context apps.

**Comment by Romanitho** [comment]
Thanks for your comment, i appreciate.
Normally, scripts already manage that, but it might not be working properly. I'll double check

**Comment by Romanitho** [comment]
```
#Get WinGet Location Function
function Get-WingetCmd {
    #Get WinGet Location in User context
    $WingetCmd = Get-Command winget.exe -ErrorAction SilentlyContinue
    if ($WingetCmd){
        $Script:winget = $WingetCmd.Source
    }
    #Get WinGet Location in System context (WinGet < 1.17)
    elseif (Test-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe\AppInstallerCLI.exe"){
        $Script:winget = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe\AppInstallerCLI.exe" | Select-Object -ExpandProperty Path
    }
    #Get WinGet Location in System context (WinGet > 1.17)
    elseif (Test-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe\winget.exe"){
        $Script:winget = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe\winget.exe" | Select-Object -ExpandProperty Path
    }
    else{
        Write-Log "Winget not installed !" "Red"
        break
    }
    Write-Log "Using following Winget Cmd: $winget"
}
```

**Comment by o-l-a-v** [comment]
Nice. Then you're ahead of me. :D

**Comment by Romanitho** [comment]
I should have shared that, sorry :/
But I discovered that when I used a pre-released version on a test machine. So I implemented that in case of real change one day, and it happened 🤷‍♂️

**Comment by o-l-a-v** [comment]
> I should have shared that, sorry :/
> But I discovered that when I used a pre-released version on a test machine. So I implemented that in case of real change one day, and it happened 🤷‍♂️

Hehe, no worries. I've know for some time too. But I thought such a breaking change would be announced. But I guess how we use it from system context is an unsupported scenario, so.

**Comment by Romanitho** [comment]
Totally agree. No official documentation about that. Regarding end user, there is no really changes.

but hey, it still works for our needs at the end 😅

**Comment by Romanitho** [comment]
By the way, I would suggest you to get my "winget location" function if you use winget with Intune, specially for autopilot. With Autopilot, you can use winget because it already exists as pre-installed app, but of course under 1.2. Only one prerequisite, MS Visual C++ 2019. Have a look on my All-in-one report.

**Comment by o-l-a-v** [comment]
Thanks. I'm looking into making a dependency package in Intune to fix such. VSredist 2022 and minimum version of App Installer (MSIX from winget-cli GitHub releases, or https://store.rg-adguard.net/).

**Comment by Romanitho** [comment]
Not sure to understand what you are trying to do.

**Comment by o-l-a-v** [comment]
> Not sure to understand what you are trying to do.

Ended up creating a requirement script that checks minium version of App Installer:

* https://github.com/o-l-a-v/winget-intune-win32/blob/main/Common/Require-AppInstallerMinimumVersion.ps1

And continue using CMD for install command, just using ```winget.exe``` instead.

But I'm considering making a standalone Win32 app that installs latest version of App Installer if required version is not met. But not in a hurry about that. Not using this for much other than research atm. :)
