### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by iMonZ** [Romanitho/Winget-Install#5]
This tool works like a charm!
Wow, this saves so many hours, thank you so much!!!

But could you add the feature for uninstalling applications?

Since most of the time, the winget uninstall command works perfectly in time!

Thanks and have a great weekend

**Comment by Romanitho** [comment]
Hey, thanks for your comment.
[Uninstall](https://github.com/Romanitho/Winget-Install#uninstall) command is supported. But it reaches the Winget uninstall limits.
Always test first :)

**Comment by iMonZ** [comment]
> Hey, thanks for your comment. [Uninstall](https://github.com/Romanitho/Winget-Install#uninstall) command is supported. But it reaches the Winget uninstall limits. Always test first :)

How can I uninstall? With the installation script? Or which arguments should I use?

**Comment by Romanitho** [comment]
powershell.exe -ExecutionPolicy bypass -File winget-install.ps1 -AppIDs _Your.App_ **-Uninstall**

**Comment by iMonZ** [comment]
Thank you so much!
