### ISSUE TITLE
Apps not detected when pushed through intune

### ISSUE THREAD

**Issue by CalicoFatCat** [Romanitho/Winget-Install#50]
When running the installer from my local account, it works fine. When trying to install 7zip via intune using `powershell.exe -Executionpolicy Bypass -File winget-install.ps1 -AppIDs 7zip.7zip`, 7zip is installed but intune reports that the install fails.  It looks like it's failing to pass the confirm-install check, I added some log output with the variables that are being passed and it appears that $InstalledApp is being assigned -\|/  -\|/- which is being compared with $AppID 7zip.7zip

12:08:43 - ###   6/16/2022 - NEW INSTALL REQUEST   ###
12:08:43 - Using following Winget Cmd: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.10941.0_x64__8wekyb3d8bbwe\winget.exe

12:08:43 - Start 7zip.7zip processing...
12:08:44 - -> 7zip.7zip exists on Winget Repository.
```
12:08:46 - -> confirm-install did not find    -\| 
   -\|/-
, 7zip.7zip
```
12:08:46 - -> Installing 7zip.7zip...
12:08:46 - -> Running: "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.10941.0_x64__8wekyb3d8bbwe\winget.exe" install --id 7zip.7zip --accept-package-agreements --accept-source-agreements -h 
   -\| 
Found 7-Zip [7zip.7zip] Version 21.07
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.7-zip.org/a/7z2107-x64.exe
   -\|/-\| 

  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  0.00 B / 1.46 MB
  ████████████████████▒▒▒▒▒▒▒▒▒▒  1024 KB / 1.46 MB
  ██████████████████████████████  1.46 MB / 1.46 MB
Successfully verified installer hash
   - 
Starting package install...
   -\| 
Successfully installed
   - 
```
12:09:28 - -> confirm-install did not find    -\|/ 
   -\|/-
, 7zip.7zip
```
12:09:28 - -> 7zip.7zip installation failed!
12:09:28 - 7zip.7zip processing finished!

12:09:29 - ###   END REQUEST   ###

**Comment by Romanitho** [comment]
Hi. It seems to work well on my side. But I use the latest Winget Preview version. Not sure it changes something

**Comment by Romanitho** [comment]
Do you still have the problem ?

**Comment by CalicoFatCat** [comment]
@Romanitho sorry for the late response. I just got around to re-testing with latest updates, it looks like it's resolved now

**Comment by Romanitho** [comment]
Thanks for your feedback
