### ISSUE TITLE
Issue running as system 

### ISSUE THREAD

**Issue by temeyers** [Romanitho/Winget-Install#53]
When running the install as system context with intune the logs show "winget not found"  
if ran as user context the app attempts to install and requests admin permissions. 

powershell.exe -Executionpolicy Bypass -File winget-install.ps1 -AppIDs "Google.Chrome --override \"/qn""

**Comment by temeyers** [comment]
The version is 1.3.1741 

As for the quotes the script doesn’t appear to even make it to that step since it fails to find winget, the same commands also work when not run with Intune. 

Terry Meyers 
Systems Administrator 
RBC Medical Innovation’s

**Comment by temeyers** [comment]
When adding the win32 app should the script be run in user or system context ? When i run in user context the user is being prompted with admin credentials but works fine if credential's are given, when run as system it fails to locate winget

**Comment by temeyers** [comment]
I appended your script to start-transcript to see what was going on and it appears that intune runs in 32 bit system context and fails to find the path as shown below, any advice ? 

`PSVersion: 5.1.19041.1682
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.19041.1682
BuildVersion: 10.0.19041.1682
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
	        888       888 d8b  .d8888b.           d8b
	        888   o   888 Y8P d88P  Y88b          Y8P
	        888  d8b  888     888    888
	        888 d888b 888 888 888        888  888 888
	        888d88888b888 888 888  88888 888  888 888
	        88888P Y88888 888 888    888 888  888 888
	        8888P   Y8888 888 Y88b  d88P Y88b 888 888
	        888P     Y888 888  "Y8888P88  "Y88888 888
	       https://github.com/Romanitho/Winget-Install
	     https://github.com/Romanitho/Winget-Install-GUI
	_________________________________________________________
18:29:24 - ###   7/7/2022 - NEW INSTALL REQUEST   ###
Resolve-Path : Cannot find path 'C:\Program Files (x86)\WindowsApps' because it does not exist.
At C:\Windows\IMECache\0a664599-7448-47db-a890-cd1dfe5c9240_4\winget-install.ps1:104 char:26
+ ... ingetPath = Resolve-Path "$env:ProgramFiles\WindowsApps\Microsoft.Des ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files (x86)\WindowsApps:String) [Resolve-Path], 
ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
Resolve-Path : Cannot find path 'C:\Program Files (x86)\WindowsApps' because it does not exist.
At C:\Windows\IMECache\0a664599-7448-47db-a890-cd1dfe5c9240_4\winget-install.ps1:104 char:26
+ ... ingetPath = Resolve-Path "$env:ProgramFiles\WindowsApps\Microsoft.Des ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program Files (x86)\WindowsApps:String) [Resolve-Path], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand
18:29:25 - Winget not installed !
PS>TerminatingError(): "System error."
>> $global:?
True`

**Comment by temeyers** [comment]
I modified this line from $env: and added a space to program files and this appears to have resolved the resolver issue.     

$ResolveWingetPath = Resolve-Path "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe"

**Comment by Romanitho** [comment]
Hi. It light be something similar to WAU when running win32 package. It calls 32 bits process and we want it to be 64. Here is the WAU explanation https://github.com/Romanitho/Winget-AutoUpdate/discussions/88#discussioncomment-2849475

**Comment by Romanitho** [comment]
Can you try to run it like this:  
`"%systemroot%\sysnative\WindowsPowerShell\v1.0\powershell.exe" -noprofile -executionpolicy bypass -file winget-install.ps1 -AppIDs Google.Chrome`

**Comment by temeyers** [comment]
Yessir that did it, sorry i didnt realize this i appreciate you !
