### ISSUE TITLE
normalize script input parameters and output for better compatibility with intune

### ISSUE THREAD

**Issue by Paul-Spagnola-Work** [Romanitho/Winget-Install#56]
I am customizing my copy of this project for use with intune. I would like to suggest a few things:

- Detection script should take the same parameter as install scripts: param($AppIDs="default value")
- I think the install script should return 0 on success. This would make it work better for intune. We could return a variable that is the sum of all installs. Returning 0 is easy when you only install one app, which is how I will package this, but for the project Install-App could increase the return code by 1 for errors and increase by 0 for success. Then return the sum.

**Comment by Paul-Spagnola-Work** [comment]
I just realized why the detect script does not accept a parameter. Should have tested that. Sorry.

 Instead I changed by Intune app build and upload script to dynamically update the detect script.

**Comment by Paul-Spagnola-Work** [comment]
apparently Get-WingetCmd is failing, because $env:programfiles = "c:\program files (x86)\"  when ran by intune, but when ran by system user from a powershell process $env:programfiles = "c:\program files\"

**Comment by Romanitho** [comment]
this is because you haven't run the PowerShell in 64 bit, no ?
Use sysnative as described

**Comment by Paul-Spagnola-Work** [comment]
You are probably right. sorry. I went back and read the instructions. None of my other intune Powershell scripts require this, so I forgot that step. I am only calling "powershell.exe" not the full path.  I will test that later.

I also noticed that the detect script is hard coded for c:\program files\, but the install script uses $env:ProgramFiles.  That is why the detect script was working properly for me, but the install script was failing.

**Comment by Romanitho** [comment]
Yes, you're right. We need to change the detection script to match install script logical.

regarding PowerShell, you usually use PowerShell natively with Intune, that is 32 bit but works for almost everything :) but WAU uses registry key that depend if it is run in 32 or 64 bits, that's why we need to specify sysnative to force 64 bit PowerShell from 32 bit cmd
