### ISSUE TITLE
We need logic to confirm Winget is on the system

### ISSUE THREAD

**Issue by SobreroD** [Romanitho/Winget-Install#58]
I have run into a few times that clients do not have Winget on the windows build. We need to have a way to first detect if Desktopappinstaller is even on the box and healthy and if not auto install/auto update. in the cases i have found if you simply navigate to the Microsoft store "app installer" it will detect it's installed but needs an update to work correctly.

**Comment by Romanitho** [comment]
Hello. In theory when we use Winget-Install it is in addition to Winget-AutoUpdate in our mind. WAU takes care about Winget install.
But we can add this feature to Winget-Install as well.
