### ISSUE TITLE
Installer Hash mismatch

### ISSUE THREAD

**Issue by sschmocker** [Romanitho/Winget-Install#6]
If there is a mismatch with the installer, then the app does not install.
Is there a option to add the "--force" command to the install command in intune? 

This bug has already been stated here:
https://github.com/microsoft/winget-cli/issues/714

**Comment by Romanitho** [comment]
You may now use the --force option ;)

**Comment by ztrhgf** [comment]
I get the same error for Ghisler.TotalCommander. It is because the latest version 10.51. The previous 10.50 works fine...

**Comment by Romanitho** [comment]
even with --force ?

**Comment by ztrhgf** [comment]
> 

Yes, force didn't help. I suppose its because I am running this as an admin.

**Comment by FaserF** [comment]
can confirm. I get the same issue when trying to install TeamViewer/Teamviewer Host

**Comment by Romanitho** [comment]
```
C:\Users\WDAGUtilityAccount>winget install TeamViewer.TeamViewer --force
Found TeamViewer [TeamViewer.TeamViewer] Version 15.34.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe
  ██████████████████████████████  43.8 MB / 43.8 MB
Installer hash does not match; this cannot be overridden when running as admin
```

You have now the answer on the last line 😇

**Comment by Romanitho** [comment]
https://github.com/microsoft/winget-cli/issues/715

**Comment by FaserF** [comment]
thanks, will wait for a fix within winget then :)

**Comment by Romanitho** [comment]
For teamviewer, I would even suggest you to use it as a "normal" package. I think there installers always point to the same URL. So obviously SHA will change each time they release a new version
