### ISSUE TITLE
UTF-16 LE

### ISSUE THREAD

**Issue by KnifMelti** [Romanitho/Winget-Install#61]
```
function Add-WAUWhiteList ($AppID) {
    #Check if WAU default intall path exists
    $WhiteList = "$WAUInstallLocation\included_apps.txt"
    if (Test-Path $WhiteList) {
        Write-Log "-> Add $AppID to WAU included_apps.txt"
        #Add App to "included_apps.txt"
        Add-Content -path $WhiteList -Value "`n$AppID" -Force
        #Remove duplicate and blank lines
        $file = Get-Content $WhiteList | Select-Object -Unique | Where-Object { $_.trim() -ne "" } | Sort-Object
        $file | Out-File $WhiteList
    }
}

```
It changes the encoding from UTF-8 to UTF -16 LE in the file and if that file is moved to a web-site then it downloads ang gets a lot of junk after every entry...

**Comment by Romanitho** [comment]
oh. I'll have a look on that

**Comment by Romanitho** [comment]
Is this fix does the trick ?  
https://github.com/Romanitho/Winget-Install/tree/fix-utf8

If yes, i'll merge :)

**Comment by KnifMelti** [comment]
'll test it as soon as possible...

**Comment by KnifMelti** [comment]
1 step closer, now it'll make an **utf-8 BOM**. Get rid of the BOM too, please!
Strange; `function Remove-WAUWhiteList ($AppID)` makes it only UTF-8 as it should be...

**Comment by Romanitho** [comment]
another try ? :)

**Comment by KnifMelti** [comment]
Ah, this is a wild goose chase.. ..sorry to have occupied your time! 🤔
Cant replicate it on other machine (none Win 11/swedish OS)...
...let it be like it was until someone else thinks it should be investigated (I'm investigation on my end).
By the way, its only critical if the file gets uploaded to web and then downloaded by WAU...
