### ISSUE TITLE
Winget-Install thinks winget program is installed but it is not

### ISSUE THREAD

**Issue by FaserF** [Romanitho/Winget-Install#71]
I am unable to install Bitwarden (other Programs work, but this specific one brings issues for me). The script says it is already installed, but it definitly is not.
Am I doing something wrong? Manually installing it via winget works.

![image](https://user-images.githubusercontent.com/12374134/208171806-ab3eae40-c430-4fa2-8fc1-1100ed2fe632.png)

**Comment by FaserF** [comment]
I have extended the script, to try a reinstallation if it is already installed and to share the install result.
I dont think its an issue with the script itself, but still weird. Winget answers it is installed, but while trying to uninstall it, it says "not installed".

````
20:46:25 - Start Bitwarden.Bitwarden processing...
20:46:27 - -> Bitwarden.Bitwarden exists on Winget Repository.
20:46:27 - -> Check App Install result:    - 
Name      Id                  Version   Source
-----------------------------------------------
Bitwarden Bitwarden.Bitwarden 2022.12.0 winget

20:46:27 - -> Bitwarden.Bitwarden is already installed. Due to ForceInstall it will now be reinstalled.
20:46:28 - -> Check App Install result:    - 
Name      Id                  Version   Source
-----------------------------------------------
Bitwarden Bitwarden.Bitwarden 2022.12.0 winget

20:46:28 - -> Uninstalling Bitwarden.Bitwarden...
20:46:28 - -> Running: "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.17.10691.0_x64__8wekyb3d8bbwe\winget.exe" uninstall --id Bitwarden.Bitwarden -e --accept-source-agreements -h
   - 
Found Bitwarden [Bitwarden.Bitwarden]
Starting package uninstall...
An unexpected error occurred while executing the command: 
0x800401f5 : Application not found.
20:46:29 - -> Check App Install result:    -\ 
Name      Id                  Version   Source
-----------------------------------------------
Bitwarden Bitwarden.Bitwarden 2022.12.0 winget

20:46:29 - -> Bitwarden.Bitwarden uninstall failed!
20:46:30 - -> Check App Install result:    - 
Name      Id                  Version   Source
-----------------------------------------------
Bitwarden Bitwarden.Bitwarden 2022.12.0 winget

20:46:30 - -> Bitwarden.Bitwarden is already installed.
````

**Comment by KnifMelti** [comment]
https://github.com/microsoft/winget-pkgs/issues/92828#issuecomment-1383172537

**Comment by KnifMelti** [comment]
And then for **WAU** under **mods**:
[Bitwarden.Bitwarden-override.txt](https://github.com/Romanitho/Winget-Install/files/10420635/Bitwarden.Bitwarden-override.txt)

**Comment by KnifMelti** [comment]
@FaserF Edited the answer above...

**Comment by FaserF** [comment]
Thank you @KnifMelti 
One question. Do I have to create the file Bitwarden.Bitwarden-override.txt manually and deploy it manually or is there a parameter I can pass anywhere so that it gets created automatically within the winget-install deployment to WAU?
Havent found a matching parameter yet (was searching the main branch).

**Comment by KnifMelti** [comment]
That is a manual work., unless...
We're using [-ModsPath](https://github.com/Romanitho/Winget-AutoUpdate#advanced-installation) to deploy our mods and **-ListPath** for the excluded/included_apps.txt
