### ISSUE TITLE
Installing Silently in User Context via Intune

### ISSUE THREAD

**Issue by LunianDE** [Romanitho/Winget-Install#81]
Hello together,

i have one question i stumbled upon. We want to install Spotify via Winget Install and distribute it via Intune. Normally we would install it as System Context, which would be automatically quiet (or atleast no powershell window opens). However, Spotify is not allowing it to install it as Systems Context or with Administrator Rights.

If we install it with User context, it works fine, but the Users see the PowerShell popping up when installing Spotify. Im talking about the PowerShell which is displaying what the Winget-Install.ps1 Script is doing. Is there any way we can disable that this powershell Window is open? We tried -NonInteractive as a PowerShell Launch Parameter, but that didn't work either, it keeps popping up.

Thank you very much!

**Comment by Romanitho** [comment]
hello. Try `powershell.exe -WindowStyle hidden`

**Comment by LunianDE** [comment]
> hello. Try `powershell.exe -WindowStyle hidden`

Thanks, that did work!

**Comment by Romanitho** [comment]
no worries :)
