### ISSUE TITLE
Detect and Install Winget Client?

### ISSUE THREAD

**Issue by yokhoe** [Romanitho/Winget-Install#82]
Hi Roman,
Does the detection capable of installing WinGet itself? Or does it simply move on from installing any of the app packages if the WinGet binary is not detected on the machine?  What do you suggest is the best way to install WinGet?  I'm attempting to add this as a step in my Task Sequence within SCCM.

Thank you in advance!

**Comment by Romanitho** [comment]
Hi,
To install winget, have a look on the Winget-AutoUpdate project and you will find `function Install-WinGet` on https://github.com/Romanitho/Winget-AutoUpdate/blob/main/Winget-AutoUpdate-Install.ps1
