### ISSUE TITLE
Is it possible to have --version introduced in the script?

### ISSUE THREAD

**Issue by prakash-indorkar** [Romanitho/Winget-Install#9]
Hi there, 

The script is working absolutely fine having no issues so far. However, I have a requirement to add a specific version of the app, so my question is, is it possible to have --version included in the winget install command? So -Version can be added as an optional parameter. With Winget-cli it is definitely possible, so might include in this script too. What do you think?

Thanks.

**Comment by Romanitho** [comment]
Hi,
I will try to work on the possibility to pass Winget "native" arguments. Like so you'll be able to pass `--version` command, and others.

**Comment by Romanitho** [comment]
Linked #4

**Comment by prakash-indorkar** [comment]
This would be excellent. Please update here once you have done that. Thanks

**Comment by Romanitho** [comment]
#20
