### ISSUE TITLE
FEATURE: Add support for using winget "--uninstall-previous" parameter

### ISSUE THREAD

**Issue by ztrhgf** [Romanitho/Winget-Install#98]
Please add support for using winget "--uninstall-previous" parameter. And possibly others.

**Comment by Romanitho** [comment]
You can already do it:
https://github.com/Romanitho/Winget-Install#use-winget-native-parameters
`powershell.exe -Executionpolicy Bypass -File winget-install.ps1 -AppIDs "App.Name --uninstall-previous"`

**Comment by ztrhgf** [comment]
I see. Sorry missed this one

**Comment by Romanitho** [comment]
no worries :)

**Comment by ztrhgf** [comment]
OK, I've tested this, but it is kind of omitted, because in case some older version of the application is installed, your script returns "X is already installed" hence nothing happens.
![image](https://github.com/Romanitho/Winget-Install/assets/2930419/5a2df0b4-5fcf-4dfd-ac0c-f8e082749071)

So if I want to remove the older version, I have to choose another approach I guess?

**Comment by Romanitho** [comment]
Very true, this is used to install an app. To maintain it, we usa WAU 
https://github.com/Romanitho/Winget-AutoUpdate

But we are thinking about adding an option to force the install.

**Comment by KnifMelti** [comment]
Can be done with an `AppID-preinstall.ps1` as a [Custom (Mods)](https://github.com/Romanitho/Winget-Install#custom-mods)
